In [5]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import seaborn as sns
import matplotlib.pyplot as plt

In [8]:
df_custoewmers = pd.read_csv("../data/CPI/consumer_price_index.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/CPI/consumer_price_index.csv'

In [3]:
for df_name, df in data.items():
    print(df_name, ':', df.shape)

df_customers : (99441, 5)
df_locations : (1000163, 5)
df_items : (112650, 7)
df_payments : (103886, 5)
df_reviews : (99224, 7)
df_orders : (99441, 8)
df_products : (32951, 9)
df_sellers : (3095, 4)
df_product_name : (71, 2)

In [4]:
df = df_orders.merge(df_items, on='order_id', how='left')

df = df.merge(df_payments, on='order_id', how='outer', validate='m:m')

df = df.merge(df_reviews, on='order_id', how='outer')

df = df.merge(df_products, on='product_id', how='outer')

df = df.merge(df_customers, on='customer_id', how='outer')

df = df.merge(df_sellers, on='seller_id', how='outer')

df.shape

(119143, 39)

In [5]:
# df.to_parquet("../data/EDA - SALES DATA/Sales/merged_data.parquet")

In [6]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,1.0,credit_card,1.0,18.12,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,3.0,voucher,1.0,2.00,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,2.0,voucher,1.0,18.59,a54f0611adc9ed256b57ede6b6eb5114,4.0,NaN,"Não testei o produto ainda, mas ele veio corre...",2017-10-11 00:00:00,2017-10-12 03:43:48,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP,9350.0,maua,SP
3,128e10d95713541c87cd1a2e48201934,a20e8105f23924cd00833fd87daa0831,delivered,2017-08-15 18:29:31,2017-08-15 20:05:16,2017-08-17 15:28:33,2017-08-18 14:44:43,2017-08-28 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-21 20:05:16,29.99,7.78,1.0,credit_card,3.0,37.77,b46f1e34512b0f4c74a72398b03ca788,4.0,NaN,Deveriam embalar melhor o produto. A caixa vei...,2017-08-19 00:00:00,2017-08-20 15:16:36,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,3a51803cc0d012c3b5dc8b7528cb05f7,3366,sao paulo,SP,9350.0,maua,SP
4,0e7e841ddf8f8f2de2bad69267ecfbcf,26c7ac168e1433912a51b924fbd34d34,delivered,2017-08-02 18:24:47,2017-08-02 18:43:15,2017-08-04 17:35:43,2017-08-07 18:30:01,2017-08-15 00:00:00,1.0,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-08-08 18:37:31,29.99,7.78,1.0,credit_card,1.0,37.77,dc90f19c2806f1abba9e72ad3c350073,5.0,NaN,"Só achei ela pequena pra seis xícaras ,mais é ...",2017-08-08 00:00:00,2017-08-08 23:26:23,utilidades_domesticas,40.0,268.0,4.0,500.0,19.0,8.0,13.0,ef0996a1a279c26e7ecbd737be23d235,2290,sao paulo,SP,9350.0,maua,SP

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119143 entries, 0 to 119142
Data columns (total 39 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   order_id                       119143 non-null  object
 1   customer_id                    119143 non-null  object
 2   order_status                   119143 non-null  object
 3   order_purchase_timestamp       119143 non-null  object
 4   order_approved_at              118966 non-null  object
 5   order_delivered_carrier_date   117057 non-null  object
 6   order_delivered_customer_date  115722 non-null  object
 7   order_estimated_delivery_date  119143 non-null  object
 8   order_item_id                  118310 non-null  float64
 9   product_id                     118310 non-null  object
 10  seller_id                      118310 non-null  object
 11  shipping_limit_date            118310 non-null  object
 12  price                          118310 non-null  float64
 13  freight_value                  118310 non-null  float64
 14  payment_sequential             119140 non-null  float64
 15  payment_type                   119140 non-null  object
 16  payment_installments           119140 non-null  float64
 17  payment_value                  119140 non-null  float64
 18  review_id                      118146 non-null  object
 19  review_score                   118146 non-null  float64
 20  review_comment_title           13989 non-null   object
 21  review_comment_message         50245 non-null   object
 22  review_creation_date           118146 non-null  object
 23  review_answer_timestamp        118146 non-null  object
 24  product_category_name          116601 non-null  object
 25  product_name_lenght            116601 non-null  float64
 26  product_description_lenght     116601 non-null  float64
 27  product_photos_qty             116601 non-null  float64
 28  product_weight_g               118290 non-null  float64
 29  product_length_cm              118290 non-null  float64
 30  product_height_cm              118290 non-null  float64
 31  product_width_cm               118290 non-null  float64
 32  customer_unique_id             119143 non-null  object
 33  customer_zip_code_prefix       119143 non-null  int64
 34  customer_city                  119143 non-null  object
 35  customer_state                 119143 non-null  object
 36  seller_zip_code_prefix         118310 non-null  float64
 37  seller_city                    118310 non-null  object
 38  seller_state                   118310 non-null  object
dtypes: float64(15), int64(1), object(23)
memory usage: 35.5+ MB

In [16]:
null = df.columns[df.isnull().sum()>0].tolist()
null_dict = {i:df[i].isnull().sum() for i in null}
null_dict

KeyError: 0

In [9]:
sorted_null = sorted(null_dict.items(), key=lambda x:x[1], reverse=True)
drop_null = [] # drop null values from col if null values is less than 1000 which is 1% of data
for i in range(len(sorted_null)):
    if sorted_null[i][1] < 1000:
        drop_null.append(sorted_null[i][0])
        
drop_null

['review_id',
 'review_score',
 'review_creation_date',
 'review_answer_timestamp',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value',
 'seller_zip_code_prefix',
 'seller_city',
 'seller_state',
 'order_approved_at',
 'payment_sequential',
 'payment_type',
 'payment_installments',
 'payment_value']

In [13]:
df = df.dropna(subset=drop_null, axis=0)

In [48]:
df[df.columns[df.isnull().sum()>0]].isnull().sum()

product_category_name         1675
product_name_lenght           1675
product_description_lenght    1675
product_photos_qty            1675
dtype: int64

In [ ]:
df.order_delivered_carrier_date = df.order_delivered_carrier_date.fillna(method='ffill', axis=0)

df.order_delivered_customer_date = df.order_delivered_customer_date.fillna(method='ffill', axis=0)

df.review_comment_title = df.review_comment_title.fillna('N/A', axis=0)

df.review_comment_message = df.review_comment_message.fillna('N/A', axis=0)

In [37]:
len(np.where((df.product_category_name.isnull() ==True)&(df.product_name_lenght.isnull() ==True)&(df.product_description_lenght.isnull() ==True)&(df.product_photos_qty.isnull() ==True))[0])

1675

In [68]:
# #all have same common null values
df.loc[df.index[np.where((df.product_category_name.isnull() ==True)&(df.product_name_lenght.isnull() ==True)&(df.product_description_lenght.isnull() ==True)&(df.product_photos_qty.isnull() ==True))[0]]]
# #can't work cuz all values are null

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value,review_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,seller_zip_code_prefix,seller_city,seller_state
2636,136cce7faa42fdb2cefd53fdc79a6098,ed0271e0b7da060a393796590e7b737a,invoiced,2017-04-11 12:22:08,2017-04-13 13:25:17,2017-04-18 15:09:26,2017-04-20 14:33:48,2017-05-09 00:00:00,1.0,a1804276d9941ac0733cfd409f5206eb,dc8798cbf453b7e0f98745e396cc5616,2017-04-19 13:25:17,49.90,16.05,1.0,credit_card,1.0,65.95,e07549ef5311abcc92ba1784b093fb56,2.0,N/A,fiquei triste por n ter me atendido.,2017-05-13 00:00:00,2017-05-13 20:25:42,NaN,NaN,NaN,NaN,600.0,35.0,35.0,15.0,36edbb3fb164b1f16485364b6fb04c73,98900,santa rosa,RS,5455.0,sao paulo,SP
2637,9c9504bb506aa1635fb6ad19be9bcfa9,5638c42751e237d265ad0c0536256311,delivered,2017-09-06 00:33:14,2017-09-08 07:03:44,2017-09-13 19:52:19,2017-09-14 16:58:54,2017-09-19 00:00:00,1.0,a1804276d9941ac0733cfd409f5206eb,dc8798cbf453b7e0f98745e396cc5616,2017-09-14 07:03:44,49.90,7.78,1.0,credit_card,1.0,57.68,42dbe41e73179a583776776f7146005a,1.0,N/A,O produto veio errado eu pedi no tamanho 44 e ...,2017-09-15 00:00:00,2017-09-19 00:35:24,NaN,NaN,NaN,NaN,600.0,35.0,35.0,15.0,f7e0fe56fc317ded1c63a772a48d0159,6112,osasco,SP,5455.0,sao paulo,SP
2654,4f53648717b48854fb9db283e2cf5d27,6f511bdde13d8de37379becebabb7fd2,delivered,2017-05-13 20:17:09,2017-05-13 20:25:11,2017-05-17 16:32:38,2017-05-19 09:27:55,2017-05-31 00:00:00,1.0,62fde58e97724f8b7519f3789eefa33f,dc8798cbf453b7e0f98745e396cc5616,2017-05-25 20:25:11,49.90,11.85,4.0,voucher,1.0,10.69,5b94961d9765588bc98c917e20a898ef,4.0,N/A,Tudo certo,2017-05-20 00:00:00,2017-05-21 11:58:45,NaN,NaN,NaN,NaN,600.0,35.0,35.0,15.0,994cd2f6a90026d5b74debc9fa41a5c6,17625,tupa,SP,5455.0,sao paulo,SP
2655,4f53648717b48854fb9db283e2cf5d27,6f511bdde13d8de37379becebabb7fd2,delivered,2017-05-13 20:17:09,2017-05-13 20:25:11,2017-05-17 16:32:38,2017-05-19 09:27:55,2017-05-31 00:00:00,1.0,62fde58e97724f8b7519f3789eefa33f,dc8798cbf453b7e0f98745e396cc5616,2017-05-25 20:25:11,49.90,11.85,2.0,voucher,1.0,16.04,5b94961d9765588bc98c917e20a898ef,4.0,N/A,Tudo certo,2017-05-20 00:00:00,2017-05-21 11:58:45,NaN,NaN,NaN,NaN,600.0,35.0,35.0,15.0,994cd2f6a90026d5b74debc9fa41a5c6,17625,tupa,SP,5455.0,sao paulo,SP
2656,4f53648717b48854fb9db283e2cf5d27,6f511bdde13d8de37379becebabb7fd2,delivered,2017-05-13 20:17:09,2017-05-13 20:25:11,2017-05-17 16:32:38,2017-05-19 09:27:55,2017-05-31 00:00:00,1.0,62fde58e97724f8b7519f3789eefa33f,dc8798cbf453b7e0f98745e396cc5616,2017-05-25 20:25:11,49.90,11.85,1.0,voucher,1.0,8.90,5b94961d9765588bc98c917e20a898ef,4.0,N/A,Tudo certo,2017-05-20 00:00:00,2017-05-21 11:58:45,NaN,NaN,NaN,NaN,600.0,35.0,35.0,15.0,994cd2f6a90026d5b74debc9fa41a5c6,17625,tupa,SP,5455.0,sao paulo,SP
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119113,c894fad29c885c81201d9bdd80cd68c5,42db86d932ba029e4e0290778ebfc59d,invoiced,2017-12-18 10:39:37,2017-12-19 09:51:49,2018-05-18 15:17:00,2018-06-11 14:03:50,2018-01-05 00:00:00,2.0,0c40401eba358c9ef2ff2df80b6eab52,3bfad056cf05c00dabe2f895925d83b1,2017-12-26 09:51:49,41.33,9.34,1.0,boleto,1.0,253.35,a0cce310b010a5ba8531952af8d2836c,1.0,N/A,Não recebi o produto até o momento. Estou no a...,2018-01-09 00:00:00,2018-01-09 03:29:32,NaN,NaN,NaN,NaN,500.0,16.0,15.0,15.0,803c530613f5c4ee03502be0d6894de0,12236,sao jose dos campos,SP,6033.0,osasco,SP
119114,c894fad29c885c81201d9bdd80cd68c5,42db86d932ba029e4e0290778ebfc59d,invoiced,2017-12-18 10:39:37,2017-12-19 09:51:49,2018-05-18 15:17:00,2018-06-11 14:03:50,2018-01-05 00:00:00,3.0,0c40401eba358c9ef2ff2df80b6eab52,3bfad056cf05c00dabe2f895925d83b1,2017-12-26 09:51:49,41.33,9.34,1.0,boleto,1.0,253.35,a0cce310b010a5ba8531952af8d2836c,1.0,N/A,Não recebi o produto até o momento. Estou no a...,2018-01-09 00:00:00,2018-01-09 03:29:32,NaN,NaN,NaN,NaN,500.0,16.0,15.0,15.0,803c530613f5c4ee03502be0d6894de0,12236,sao jose dos campos,SP,6033.0,osasco,SP
119115,c894fad29c885c81201d9bdd80cd68c5,42db86d932ba029e4e0290778ebfc59d,invoiced,2017-12-18 10:39:37,2017-12-19 09:51:49,2018-05-18 15:17:00,2018-06-11 14:03:50,2018-01-05 00:00:00,4.0,0c40401eba358c9ef2ff2df80b6eab52,3bfad056cf05c00dabe2f895925d83b1,2017-12-26 09:51:49,41.33,9.34,1.0,boleto,1.0,253.35,a0cce310b010a5ba8531952af8d2836c,1.0,N/A,Não recebi o produto até o momento. Estou no a...,2018-01-09 00:00:00,2018-01-09 03:29:32,NaN,NaN,NaN,NaN,500.0,16.0,15.0,15.0,803c530613f5c4ee03502be0d6894de0,12236,sao jose dos campos,SP,6033.0,osasco,SP
119116,c894fad29c885c81201d9bdd80cd68c5,42db86d932ba029e4e0290778ebfc59d,invoiced,2017-12-18 10:39:37,2017-12-19 09:51:49,2018-05-18 15:17:00,2018-06-11 14:03:50,2018-01-05 00:00:00,5.0,0c40401eba358c9ef2ff2df80b6eab52,3bfad056cf05c00dabe2f895925d83b1,2017-12-26 09:51:49,41.33,9.34,1.0,boleto,1.0,253.35,a0cce310b010a5ba8531952af8d2836c,1.0,N/A,Não recebi o produto até o momento. Estou no a...,2018-01-09 00:00:00,2018-01-09 03:29:32,NaN,NaN,NaN,NaN,500.0,16.0,15.0,15.0,803c530613f5c4ee03502be0d6894de0,12236,sao jose dos campos,SP,6033.0,osasco,SP
119130,b1866dace5f7daf46e4ef10ed7c3a5e9,eb6cafe1788b71c7e4d0fb96b62c6cb7,delivered,2017-11-20 12:49:35,2017-11-20 13:07:31,2017-11-21 22:55:36,2017-12-27 00:06:56,2017-12-18 00:00:00,1.0,f22ccf28078d6ba8961033bc6a20bc12,9ef932e837d8b7f392c0bfee9d359dc2,2017-11-24 13:07:31,59.90,19.66,1.0,credit_card,2.0,79.56,e5162d9f0c4aa94b9147401eef42faac,3.0,N/A,N/A,2017-12-19 00:00:00,2017-12-19 10:31:54,NaN,NaN,NaN,NaN,1500.0,30.0,10.0,36.0,79d29011de7460db03cea0f936e521bf,78840,campo verde,MT,14940.0,ibitinga,SP

In [72]:
df.product_category_name.value_counts() #no product has been purchased single time wow!
# fas all 4 has same null we should fill them by "null_name"  ->> everything normal just it doesnot have basic name and lenght
df[['product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty']] = df[['product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty']].fillna("null_name", axis=0)
df.isnull().sum().sum()

0

order_id                         0
customer_id                      0
order_status                     0
order_purchase_timestamp         0
order_approved_at                0
order_delivered_carrier_date     0
order_delivered_customer_date    0
order_estimated_delivery_date    0
order_item_id                    0
product_id                       0
seller_id                        0
shipping_limit_date              0
price                            0
freight_value                    0
payment_sequential               0
payment_type                     0
payment_installments             0
payment_value                    0
review_id                        0
review_score                     0
review_comment_title             0
review_comment_message           0
review_creation_date             0
review_answer_timestamp          0
product_category_name            0
product_name_lenght              0
product_description_lenght       0
product_photos_qty               0
product_weight_g                 0
product_length_cm                0
product_height_cm                0
product_width_cm                 0
customer_unique_id               0
customer_zip_code_prefix         0
customer_city                    0
customer_state                   0
seller_zip_code_prefix           0
seller_city                      0
seller_state                     0
dtype: int64