In [1]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("../../data/CPI/consumer_price_index.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Columns: 1719 entries, FREQ to 2024-10
dtypes: float64(1712), int64(1), object(6)
memory usage: 3.3+ MB

In [6]:
df.head()

,FREQ,Frequency,REF_AREA,Reference area,UNIT_MEASURE,Unit of measure,TIME_FORMAT,Time Format,BREAKS,COVERAGE,DECIMALS,Decimals,TITLE_TS,Series,1661,1662,1663,1664,1665,1666,1667,1668,1669,1670,1671,1672,1673,1674,1675,1676,1677,1678,1679,1680,1681,1682,1683,1684,1685,1686,1687,1688,1689,1690,1691,1692,1693,1694,1695,1696,1697,1698,1699,1700,1701,1702,1703,1704,1705,1706,1707,1708,1709,1710,1711,1712,1713,1714,1715,1716,1717,1718,1719,1720,1721,1722,1723,1724,1725,1726,1727,1728,1729,1730,1731,1732,1733,1734,1735,1736,1737,1738,1739,1740,1741,1742,1743,1744,1745,1746,1747,1748,1749,1750,1751,1752,1753,1754,1755,1756,1757,1758,1759,1760,1761,1762,1763,1764,1765,1766,1767,1768,1769,1770,1771,1772,1773,1774,1775,1776,1777,1778,1779,1780,1781,1782,1783,1784,1785,1786,1787,1788,1789,1790,1791,1792,1793,1794,1795,1796,1797,1798,1799,1800,1801,1802,1803,1804,1805,1806,1807,1808,1809,1810,1811,1812,1813,1814,1815,1816,1817,1818,1819,1820,1821,1822,1823,1824,1825,1826,1827,1828,1829,1830,1831,1832,1833,1834,1835,1836,1837,1838,1839,1840,1841,1842,1843,1844,1845,1846,1847,1848,1849,1850,1851,1852,1853,1854,1855,1856,1857,1858,1859,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869,1870,1871,1872,1873,1874,1875,1876,1877,1878,1879,1880,1881,1882,1883,1884,1885,1886,1887,1888,1889,1890,1891,1892,1893,1894,1895,1896,1897,1898,1899,1900,1901,1902,1903,1904,1905,1906,1907,1908,1909,1910,1911,1912,1913,1913-01,1913-02,1913-03,1913-04,1913-05,1913-06,1913-07,1913-08,1913-09,1913-10,1913-11,1913-12,1914,1914-01,1914-02,1914-03,1914-04,1914-05,1914-06,1914-07,1914-08,1914-09,1914-10,1914-11,1914-12,1915,1915-01,1915-02,1915-03,1915-04,1915-05,1915-06,1915-07,1915-08,1915-09,1915-10,1915-11,1915-12,1916,1916-01,1916-02,1916-03,1916-04,1916-05,1916-06,1916-07,1916-08,1916-09,1916-10,1916-11,1916-12,1917,1917-01,1917-02,1917-03,1917-04,1917-05,1917-06,1917-07,1917-08,1917-09,1917-10,1917-11,1917-12,1918,1918-01,1918-02,1918-03,1918-04,1918-05,1918-06,1918-07,1918-08,1918-09,1918-10,1918-11,1918-12,1919,1919-01,1919-02,1919-03,1919-04,1919-05,1919-06,1919-07,1919-08,1919-09,1919-10,1919-11,1919-12,1920,1920-01,1920-02,1920-03,1920-04,1920-05,1920-06,1920-07,1920-08,1920-09,1920-10,1920-11,1920-12,1921,1921-01,1921-02,1921-03,1921-04,1921-05,1921-06,1921-07,1921-08,1921-09,1921-10,1921-11,1921-12,1922,1922-01,1922-02,1922-03,1922-04,1922-05,1922-06,1922-07,1922-08,1922-09,1922-10,1922-11,1922-12,1923,1923-01,1923-02,1923-03,1923-04,1923-05,1923-06,1923-07,1923-08,1923-09,1923-10,1923-11,1923-12,1924,1924-01,1924-02,1924-03,1924-04,1924-05,1924-06,1924-07,1924-08,1924-09,1924-10,1924-11,1924-12,1925,1925-01,1925-02,1925-03,1925-04,1925-05,1925-06,1925-07,1925-08,1925-09,1925-10,1925-11,1925-12,1926,1926-01,1926-02,1926-03,1926-04,1926-05,1926-06,1926-07,1926-08,1926-09,1926-10,1926-11,1926-12,1927,1927-01,1927-02,1927-03,1927-04,1927-05,1927-06,1927-07,1927-08,1927-09,1927-10,1927-11,1927-12,1928,1928-01,1928-02,1928-03,1928-04,1928-05,1928-06,1928-07,1928-08,1928-09,1928-10,1928-11,1928-12,1929,1929-01,1929-02,1929-03,1929-04,1929-05,1929-06,1929-07,1929-08,1929-09,1929-10,1929-11,1929-12,1930,1930-01,1930-02,1930-03,1930-04,1930-05,1930-06,1930-07,1930-08,1930-09,1930-10,1930-11,1930-12,1931,1931-01,1931-02,1931-03,1931-04,1931-05,1931-06,1931-07,1931-08,1931-09,1931-10,1931-11,1931-12,1932,1932-01,1932-02,1932-03,1932-04,1932-05,1932-06,1932-07,1932-08,1932-09,1932-10,1932-11,1932-12,1933,1933-01,1933-02,1933-03,1933-04,1933-05,1933-06,1933-07,1933-08,1933-09,1933-10,1933-11,1933-12,1934,1934-01,1934-02,1934-03,1934-04,1934-05,1934-06,1934-07,1934-08,1934-09,1934-10,1934-11,1934-12,1935,1935-01,1935-02,1935-03,1935-04,1935-05,1935-06,1935-07,1935-08,1935-09,1935-10,1935-11,1935-12,1936,1936-01,1936-02,1936-03,1936-04,1936-05,1936-06,1936-07,1936-08,1936-09,1936-10,1936-11,1936-12,1937,1937-01,1937-02,1937-03,1937-04,1937-05,1937-06,1937-07,1937-08,1937-09,1937-10,1937-11,1937-12,1938,1938-01,1938-02,1938-03,1938-04,1938-05,1938-06,1938-07,1938-08,1938-09,1938-10,1938-11,1938-12,1939,1939-01,1939-02,1939-03,1939-04,1939-05,1939-06,1939-07,1939-08,1939-09,1939-10,1939-11,1939-12,1940,1940-01,1940-02,1940-03,1940-04,1940-05,1940-06,1940-07,1940-08,1940-09,1940-10,1940-11,1940-12,1941,1941-01,1941-02,1941-03,1941-04,1941-05,1941-06,1941-07,1941-08,1941-09,1941-10,1941-11,1941-12,1942,1942-01,1942-02,1942-03,1942-04,1942-05,1942-06,1942-07,1942-08,1942-09,1942-10,1942-11,1942-12,1943,1943-01,1943-02,1943-03,1943-04,1943-05,1943-06,1943-07,1943-08,1943-09,1943-10,1943-11,1943-12,1944,1944-01,1944-02,1944-03,1944-04,1944-05,1944-06,1944-07,1944-08,1944-09,1944-10,1944-11,1944-12,1945,1945-01,1945-02,1945-03,1945-04,1945-05,1945-06,1945-07,1945-08,1945-09,1945-10,1945-11,1945-12,1946,1946-01,1946-02,1946-03,1946-04,1946-05,1946-06,1946-07,1946-08,1946-09,1946-10,1946-11,1946-12,1947,1947-01,1947-02,1947-03,1947-04,1947-05,1947-06,1947-07,1947-08,1947-09,1947-10,1947-11,1947-12,1948,1948-01,1948-02,1948-03,1948-04,1948-05,1948-06,1948-07,1948-08,1948-09,1948-10,1948-11,1948-12,1949,1949-01,1949-02,1949-03,1949-04,1949-05,1949-06,1949-07,1949-08,1949-09,1949-10,1949-11,1949-12,1950,1950-01,1950-02,1950-03,1950-04,1950-05,1950-06,1950-07,1950-08,1950-09,1950-10,1950-11,1950-12,1951,1951-01,1951-02,1951-03,1951-04,1951-05,1951-06,1951-07,1951-08,1951-09,1951-10,1951-11,1951-12,1952,1952-01,1952-02,1952-03,1952-04,1952-05,1952-06,1952-07,1952-08,1952-09,1952-10,1952-11,1952-12,1953,1953-01,1953-02,1953-03,1953-04,1953-05,1953-06,1953-07,1953-08,1953-09,1953-10,1953-11,1953-12,1954,1954-01,1954-02,1954-03,1954-04,1954-05,1954-06,1954-07,1954-08,1954-09,1954-10,1954-11,1954-12,1955,1955-01,1955-02,1955-03,1955-04,1955-05,1955-06,1955-07,1955-08,1955-09,1955-10,1955-11,1955-12,1956,1956-01,1956-02,1956-03,1956-04,1956-05,1956-06,1956-07,1956-08,1956-09,1956-10,1956-11,1956-12,1957,1957-01,1957-02,1957-03,1957-04,1957-05,1957-06,1957-07,1957-08,1957-09,1957-10,1957-11,1957-12,1958,1958-01,1958-02,1958-03,1958-04,1958-05,1958-06,1958-07,1958-08,1958-09,1958-10,1958-11,1958-12,1959,1959-01,1959-02,1959-03,1959-04,1959-05,1959-06,1959-07,1959-08,1959-09,1959-10,1959-11,1959-12,1960,1960-01,1960-02,1960-03,1960-04,1960-05,1960-06,1960-07,1960-08,1960-09,1960-10,1960-11,1960-12,1961,1961-01,1961-02,1961-03,1961-04,1961-05,1961-06,1961-07,1961-08,1961-09,1961-10,1961-11,1961-12,1962,1962-01,1962-02,1962-03,1962-04,1962-05,1962-06,1962-07,1962-08,1962-09,1962-10,1962-11,1962-12,1963,1963-01,1963-02,1963-03,1963-04,1963-05,1963-06,1963-07,1963-08,1963-09,1963-10,1963-11,1963-12,1964,1964-01,1964-02,1964-03,1964-04,1964-05,1964-06,1964-07,1964-08,1964-09,1964-10,1964-11,1964-12,1965,1965-01,1965-02,1965-03,1965-04,1965-05,1965-06,1965-07,1965-08,1965-09,1965-10,1965-11,1965-12,1966,1966-01,1966-02,1966-03,1966-04,1966-05,1966-06,1966-07,1966-08,1966-09,1966-10,1966-11,1966-12,1967,1967-01,1967-02,1967-03,1967-04,1967-05,1967-06,1967-07,1967-08,1967-09,1967-10,1967-11,1967-12,1968,1968-01,1968-02,1968-03,1968-04,1968-05,1968-06,1968-07,1968-08,1968-09,1968-10,1968-11,1968-12,1969,1969-01,1969-02,1969-03,1969-04,1969-05,1969-06,1969-07,1969-08,1969-09,1969-10,1969-11,1969-12,1970,1970-01,1970-02,1970-03,1970-04,1970-05,1970-06,1970-07,1970-08,1970-09,1970-10,1970-11,1970-12,1971,1971-01,1971-02,1971-03,1971-04,1971-05,1971-06,1971-07,1971-08,1971-09,1971-10,1971-11,1971-12,1972,1972-01,1972-02,1972-03,1972-04,1972-05,1972-06,1972-07,1972-08,1972-09,1972-10,1972-11,1972-12,1973,1973-01,1973-02,1973-03,1973-04,1973-05,1973-06,1973-07,1973-08,1973-09,1973-10,1973-11,1973-12,1974,1974-01,1974-02,1974-03,1974-04,1974-05,1974-06,1974-07,1974-08,1974-09,1974-10,1974-11,1974-12,1975,1975-01,1975-02,1975-03,1975-04,1975-05,1975-06,1975-07,1975-08,1975-09,1975-10,1975-11,1975-12,1976,1976-01,1976-02,1976-03,1976-04,1976-05,1976-06,1976-07,1976-08,1976-09,1976-10,1976-11,1976-12,1977,1977-01,1977-02,1977-03,1977-04,1977-05,1977-06,1977-07,1977-08,1977-09,1977-10,1977-11,1977-12,1978,1978-01,1978-02,1978-03,1978-04,1978-05,1978-06,1978-07,1978-08,1978-09,1978-10,1978-11,1978-12,1979,1979-01,1979-02,1979-03,1979-04,1979-05,1979-06,1979-07,1979-08,1979-09,1979-10,1979-11,1979-12,1980,1980-01,1980-02,1980-03,1980-04,1980-05,1980-06,1980-07,1980-08,1980-09,1980-10,1980-11,1980-12,1981,1981-01,1981-02,1981-03,1981-04,1981-05,1981-06,1981-07,1981-08,1981-09,1981-10,1981-11,1981-12,1982,1982-01,1982-02,1982-03,1982-04,1982-05,1982-06,1982-07,1982-08,1982-09,1982-10,1982-11,1982-12,1983,1983-01,1983-02,1983-03,1983-04,1983-05,1983-06,1983-07,1983-08,1983-09,1983-10,1983-11,1983-12,1984,1984-01,1984-02,1984-03,1984-04,1984-05,1984-06,1984-07,1984-08,1984-09,1984-10,1984-11,1984-12,1985,1985-01,1985-02,1985-03,1985-04,1985-05,1985-06,1985-07,1985-08,1985-09,1985-10,1985-11,1985-12,1986,1986-01,1986-02,1986-03,1986-04,1986-05,1986-06,1986-07,1986-08,1986-09,1986-10,1986-11,1986-12,1987,1987-01,1987-02,1987-03,1987-04,1987-05,1987-06,1987-07,1987-08,1987-09,1987-10,1987-11,1987-12,1988,1988-01,1988-02,1988-03,1988-04,1988-05,1988-06,1988-07,1988-08,1988-09,1988-10,1988-11,1988-12,1989,1989-01,1989-02,1989-03,1989-04,1989-05,1989-06,1989-07,1989-08,1989-09,1989-10,1989-11,1989-12,1990,1990-01,1990-02,1990-03,1990-04,1990-05,1990-06,1990-07,1990-08,1990-09,1990-10,1990-11,1990-12,1991,1991-01,1991-02,1991-03,1991-04,1991-05,1991-06,1991-07,1991-08,1991-09,1991-10,1991-11,1991-12,1992,1992-01,1992-02,1992-03,1992-04,1992-05,1992-06,1992-07,1992-08,1992-09,1992-10,1992-11,1992-12,1993,1993-01,1993-02,1993-03,1993-04,1993-05,1993-06,1993-07,1993-08,1993-09,1993-10,1993-11,1993-12,1994,1994-01,1994-02,1994-03,1994-04,1994-05,1994-06,1994-07,1994-08,1994-09,1994-10,1994-11,1994-12,1995,1995-01,1995-02,1995-03,1995-04,1995-05,1995-06,1995-07,1995-08,1995-09,1995-10,1995-11,1995-12,1996,1996-01,1996-02,1996-03,1996-04,1996-05,1996-06,1996-07,1996-08,1996-09,1996-10,1996-11,1996-12,1997,1997-01,1997-02,1997-03,1997-04,1997-05,1997-06,1997-07,1997-08,1997-09,1997-10,1997-11,1997-12,1998,1998-01,1998-02,1998-03,1998-04,1998-05,1998-06,1998-07,1998-08,1998-09,1998-10,1998-11,1998-12,1999,1999-01,1999-02,1999-03,1999-04,1999-05,1999-06,1999-07,1999-08,1999-09,1999-10,1999-11,1999-12,2000,2000-01,2000-02,2000-03,2000-04,2000-05,2000-06,2000-07,2000-08,2000-09,2000-10,2000-11,2000-12,2001,2001-01,2001-02,2001-03,2001-04,2001-05,2001-06,2001-07,2001-08,2001-09,2001-10,2001-11,2001-12,2002,2002-01,2002-02,2002-03,2002-04,2002-05,2002-06,2002-07,2002-08,2002-09,2002-10,2002-11,2002-12,2003,2003-01,2003-02,2003-03,2003-04,2003-05,2003-06,2003-07,2003-08,2003-09,2003-10,2003-11,2003-12,2004,2004-01,2004-02,2004-03,2004-04,2004-05,2004-06,2004-07,2004-08,2004-09,2004-10,2004-11,2004-12,2005,2005-01,2005-02,2005-03,2005-04,2005-05,2005-06,2005-07,2005-08,2005-09,2005-10,2005-11,2005-12,2006,2006-01,2006-02,2006-03,2006-04,2006-05,2006-06,2006-07,2006-08,2006-09,2006-10,2006-11,2006-12,2007,2007-01,2007-02,2007-03,2007-04,2007-05,2007-06,2007-07,2007-08,2007-09,2007-10,2007-11,2007-12,2008,2008-01,2008-02,2008-03,2008-04,2008-05,2008-06,2008-07,2008-08,2008-09,2008-10,2008-11,2008-12,2009,2009-01,2009-02,2009-03,2009-04,2009-05,2009-06,2009-07,2009-08,2009-09,2009-10,2009-11,2009-12,2010,2010-01,2010-02,2010-03,2010-04,2010-05,2010-06,2010-07,2010-08,2010-09,2010-10,2010-11,2010-12,2011,2011-01,2011-02,2011-03,2011-04,2011-05,2011-06,2011-07,2011-08,2011-09,2011-10,2011-11,2011-12,2012,2012-01,2012-02,2012-03,2012-04,2012-05,2012-06,2012-07,2012-08,2012-09,2012-10,2012-11,2012-12,2013,2013-01,2013-02,2013-03,2013-04,2013-05,2013-06,2013-07,2013-08,2013-09,2013-10,2013-11,2013-12,2014,2014-01,2014-02,2014-03,2014-04,2014-05,2014-06,2014-07,2014-08,2014-09,2014-10,2014-11,2014-12,2015,2015-01,2015-02,2015-03,2015-04,2015-05,2015-06,2015-07,2015-08,2015-09,2015-10,2015-11,2015-12,2016,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08,2016-09,2016-10,2016-11,2016-12,2017,2017-01,2017-02,2017-03,2017-04,2017-05,2017-06,2017-07,2017-08,2017-09,2017-10,2017-11,2017-12,2018,2018-01,2018-02,2018-03,2018-04,2018-05,2018-06,2018-07,2018-08,2018-09,2018-10,2018-11,2018-12,2019,2019-01,2019-02,2019-03,2019-04,2019-05,2019-06,2019-07,2019-08,2019-09,2019-10,2019-11,2019-12,2020,2020-01,2020-02,2020-03,2020-04,2020-05,2020-06,2020-07,2020-08,2020-09,2020-10,2020-11,2020-12,2021,2021-01,2021-02,2021-03,2021-04,2021-05,2021-06,2021-07,2021-08,2021-09,2021-10,2021-11,2021-12,2022,2022-01,2022-02,2022-03,2022-04,2022-05,2022-06,2022-07,2022-08,2022-09,2022-10,2022-11,2022-12,2023,2023-01,2023-02,2023-03,2023-04,2023-05,2023-06,2023-07,2023-08,2023-09,2023-10,2023-11,2023-12,2024-01,2024-02,2024-03,2024-04,2024-05,2024-06,2024-07,2024-08,2024-09,2024-10
0,A,Annual,ES,Spain,771,"Year-on-year changes, in per cent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,A:ES:771,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.877253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.852659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.772456,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.378949,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.309781,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.177758,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.809258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.706481,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.743698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.979253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.214130,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.240370,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.391633,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.954365,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.160347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.731143,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.236886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.272289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.416707,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.680378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.953285,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.624880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.538052,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.773685,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.660226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.561909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.549351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14.414987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.174085,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.280269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.814454,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.794939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.248023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.837267,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.791436,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.721822,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.934214,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.924531,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.569073,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.718413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.673804,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.558843,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.971078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.834330,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.310346,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.433517,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.589897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.067403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.038888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.039249,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.368814,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.515576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.786797,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.075343,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.287813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.799865,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.196102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.446128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.408581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.151115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.500366,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.202598,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.956076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.674981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.699519,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.322753,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.093135,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.390576,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.532361,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.T.()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,230,231,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251
FREQ,A,M,M,A,M,M,A,M,M,M,A,A,M,M,A,A,M,M,A,M,A,M,A,M,M,A,A,M,A,A,M,M,M,M,A,M,A,M,M,M,A,A,M,A,A,M,A,M,M,A,M,M,A,A,M,M,A,A,M,A,M,M,A,A,M,A,A,M,M,A,A,M,A,A,M,M,M,A,A,M,A,A,M,M,A,A,A,M,A,M,A,M,A,A,M,A,A,A,M,M,A,M,A,M,A,M,M,A,M,A,M,A,A,A,M,A,A,M,A,M,M,M,A,M,A,A,M,M,A,A,M,A,A,M,A,M,M,M,A,M,A,M,A,A,M,M,A,M,A,M,A,M,M,M,M,M,A,M,A,A,M,A,M,A,M,A,M,A,M,M,M,A,A,M,A,A,M,A,M,A,M,A,M,M,M,M,A,A,M,A,A,M,A,A,M,M,A,M,A,M,A,M,A,A,M,A,A,M,A,A,M,A,M,A,M,M,A,A,M,A,A,M,M,A,M,A,M,M,A,A,M,A,M,A,A,M,A,A,M,A,M,M,A,M,A,M,A,A,M,A,M,A
Frequency,Annual,Monthly,Monthly,Annual,Monthly,Monthly,Annual,Monthly,Monthly,Monthly,Annual,Annual,Monthly,Monthly,Annual,Annual,Monthly,Monthly,Annual,Monthly,Annual,Monthly,Annual,Monthly,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Monthly,Monthly,Monthly,Annual,Monthly,Annual,Monthly,Monthly,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Annual,Monthly,Monthly,Annual,Monthly,Monthly,Annual,Annual,Monthly,Monthly,Annual,Annual,Monthly,Annual,Monthly,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Monthly,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Monthly,Annual,Annual,Annual,Monthly,Annual,Monthly,Annual,Monthly,Annual,Annual,Monthly,Annual,Annual,Annual,Monthly,Monthly,Annual,Monthly,Annual,Monthly,Annual,Monthly,Monthly,Annual,Monthly,Annual,Monthly,Annual,Annual,Annual,Monthly,Annual,Annual,Monthly,Annual,Monthly,Monthly,Monthly,Annual,Monthly,Annual,Annual,Monthly,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Annual,Monthly,Monthly,Monthly,Annual,Monthly,Annual,Monthly,Annual,Annual,Monthly,Monthly,Annual,Monthly,Annual,Monthly,Annual,Monthly,Monthly,Monthly,Monthly,Monthly,Annual,Monthly,Annual,Annual,Monthly,Annual,Monthly,Annual,Monthly,Annual,Monthly,Annual,Monthly,Monthly,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Annual,Monthly,Annual,Monthly,Annual,Monthly,Monthly,Monthly,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Monthly,Annual,Monthly,Annual,Monthly,Annual,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Annual,Monthly,Annual,Monthly,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Monthly,Annual,Monthly,Annual,Monthly,Monthly,Annual,Annual,Monthly,Annual,Monthly,Annual,Annual,Monthly,Annual,Annual,Monthly,Annual,Monthly,Monthly,Annual,Monthly,Annual,Monthly,Annual,Annual,Monthly,Annual,Monthly,Annual
REF_AREA,ES,PL,AT,NO,BE,SK,RU,HR,JP,DK,CN,IL,ZA,MX,LU,FI,PT,BG,NZ,HU,AR,TH,SA,KR,DZ,CO,IN,MY,LV,FR,RO,AU,BR,CH,PE,TR,SE,ID,KW,EE,CY,IS,NL,MA,GB,RS,AE,CA,CL,PH,IE,US,GR,SG,LT,ES,CZ,IT,NO,MK,RU,CN,PL,SI,IL,AT,HK,LU,FI,DE,JP,NZ,MT,XM,SA,AR,CO,BE,PT,IN,HR,SK,LV,FR,DK,KR,ZA,PE,MX,SE,BG,CY,RO,TH,IS,AU,HU,CH,MA,GB,DZ,AE,KW,PH,MY,SG,GR,BR,CZ,RS,IT,ID,TR,CL,MK,EE,LT,PL,NL,AT,HK,SI,CA,DE,RU,US,JP,XM,IE,CN,MT,ES,LU,PT,NO,BE,SK,HR,AR,DK,SA,KR,IL,CO,MX,ZA,FI,BG,LV,RO,NZ,AU,HU,TH,CH,DZ,SE,KW,IN,CY,MY,FR,BR,MA,RS,PE,TR,AE,ID,CL,EE,GR,SG,LT,IS,CZ,NL,GB,CA,MK,RU,PH,IE,US,CN,ES,SI,HK,LU,IT,DE,NO,MT,XM,SA,AR,PL,IL,AT,CO,BE,FI,HR,SK,LV,JP,DK,NZ,ZA,MX,SE,PT,IN,BG,CY,FR,TH,HU,MA,KR,DZ,PE,AE,MY,SG,RO,GR,IS,AU,BR,CZ,CH,GB,ID,TR,MK,KW,EE,PH,NL,HK,SI,RS,IT,CA,DE,CL,US,XM,IE,MT,LT
Reference area,Spain,Poland,Austria,Norway,Belgium,Slovakia,Russia,Croatia,Japan,Denmark,China,Israel,South Africa,Mexico,Luxembourg,Finland,Portugal,Bulgaria,New Zealand,Hungary,Argentina,Thailand,Saudi Arabia,Korea,Algeria,Colombia,India,Malaysia,Latvia,France,Romania,Australia,Brazil,Switzerland,Peru,Türkiye,Sweden,Indonesia,Kuwait,Estonia,Cyprus,Iceland,Netherlands,Morocco,United Kingdom,Serbia,United Arab Emirates,Canada,Chile,Philippines,Ireland,United States,Greece,Singapore,Lithuania,Spain,Czechia,Italy,Norway,North Macedonia,Russia,China,Poland,Slovenia,Israel,Austria,Hong Kong SAR,Luxembourg,Finland,Germany,Japan,New Zealand,Malta,Euro area,Saudi Arabia,Argentina,Colombia,Belgium,Portugal,India,Croatia,Slovakia,Latvia,France,Denmark,Korea,South Africa,Peru,Mexico,Sweden,Bulgaria,Cyprus,Romania,Thailand,Iceland,Australia,Hungary,Switzerland,Morocco,United Kingdom,Algeria,United Arab Emirates,Kuwait,Philippines,Malaysia,Singapore,Greece,Brazil,Czechia,Serbia,Italy,Indonesia,Türkiye,Chile,North Macedonia,Estonia,Lithuania,Poland,Netherlands,Austria,Hong Kong SAR,Slovenia,Canada,Germany,Russia,United States,Japan,Euro area,Ireland,China,Malta,Spain,Luxembourg,Portugal,Norway,Belgium,Slovakia,Croatia,Argentina,Denmark,Saudi Arabia,Korea,Israel,Colombia,Mexico,South Africa,Finland,Bulgaria,Latvia,Romania,New Zealand,Australia,Hungary,Thailand,Switzerland,Algeria,Sweden,Kuwait,India,Cyprus,Malaysia,France,Brazil,Morocco,Serbia,Peru,Türkiye,United Arab Emirates,Indonesia,Chile,Estonia,Greece,Singapore,Lithuania,Iceland,Czechia,Netherlands,United Kingdom,Canada,North Macedonia,Russia,Philippines,Ireland,United States,China,Spain,Slovenia,Hong Kong SAR,Luxembourg,Italy,Germany,Norway,Malta,Euro area,Saudi Arabia,Argentina,Poland,Israel,Austria,Colombia,Belgium,Finland,Croatia,Slovakia,Latvia,Japan,Denmark,New Zealand,South Africa,Mexico,Sweden,Portugal,India,Bulgaria,Cyprus,France,Thailand,Hungary,Morocco,Korea,Algeria,Peru,United Arab Emirates,Malaysia,Singapore,Romania,Greece,Iceland,Australia,Brazil,Czechia,Switzerland,United Kingdom,Indonesia,Türkiye,North Macedonia,Kuwait,Estonia,Philippines,Netherlands,Hong Kong SAR,Slovenia,Serbia,Italy,Canada,Germany,Chile,United States,Euro area,Ireland,Malta,Lithuania
UNIT_MEASURE,771,628,628,771,771,771,628,771,628,771,628,771,771,771,628,771,628,771,771,771,628,771,628,628,771,628,771,771,628,771,628,628,771,628,771,771,628,771,628,771,628,771,771,628,771,628,628,771,628,771,771,771,628,628,628,771,628,771,771,628,628,628,771,628,771,771,628,628,771,628,771,771,628,628,628,628,628,628,771,771,628,628,628,771,628,771,628,771,628,628,628,628,771,628,771,771,628,771,628,771,628,628,771,771,628,628,628,628,628,771,771,628,628,771,628,628,771,771,628,771,628,628,628,628,771,628,771,628,628,771,628,628,771,771,628,628,628,628,771,628,771,771,628,771,628,628,628,628,771,771,628,771,628,628,771,628,771,771,628,771,628,628,628,771,771,628,628,771,628,771,628,771,771,771,628,771,628,628,628,771,771,628,628,628,771,628,771,771,771,628,771,628,771,771,771,771,628,628,628,771,771,628,771,771,771,628,771,628,771,771,771,628,628,771,771,628,771,771,771,628,771,628,771,771,771,628,771,628,628,771,771,628,628,771,771,771,628,771,628,771,771,771,628,628,771,771,628,771,771,771,771,628

In [10]:
df.T.duplicated("Reference area")

KeyError: Index(['Reference area'], dtype='object')